py:class sqlalchemy.ext.declarative.api.Base
py:exc ValueError
